### ISSUE TITLE
[Question] Is this compatible with modern versions of Windows?

### ISSUE THREAD

**Issue by kulkom** [AlienCowEatCake/wpa_supplicant-windows#2]
Hi!

I'm currently trying to connect an old Acer Aspire V3 laptop from 2013 with a Qualcomm Atheros AR5BWB222 Wi-Fi card to a WPA3 network. Since the drivers for that card don't support WPA3, I'm trying to use wpa_supplicant-windows instead, but so far I've had no success with it either. So my question is: Does wpa_supplicant-windows support modern Windows versions like 10 or 11?

Thank you in advance.

**Comment by AlienCowEatCake** [comment]
Hi!

1. WinPcap [is deprecated since 2018](https://www.winpcap.org/news.htm). Modern Npcap alternative is not supported in this port yet.
2. In 2014, we were able to run the wpa_supplicant on Windows 8.1. However, then there were many difficulties due to drivers incompatibilities. Drivers that wpa_supplicant worked with didn't work correctly on Windows supplicant and vice versa.
3. Most likely, WPA3 will not work without drivers support. Especially when you consider that the NDIS driver interface in wpa_supplicant was abandoned before the creation of WPA3. WPA2 doesn't work without driver support definitely.
4. Binary files are compiled by MSVC 2005 and do not contain manifests for working with modern systems, which will lead to problems with the Windows Registry (however, the standalone version may work if run it as an administrator).

So I would not recommend using this port for newer versions of Windows

**Comment by kulkom** [comment]
Understood, thank you so much for your highly detailed answer.
